/* Generated by scripts/generate-phosphor-icons.ts. Do not edit by hand. */
/* Source: @phosphor-icons/core@2.1.1. */
/* Source digest: 0f5e90483d0d3efa8b4056ba289df23e01d7c23c2a2a8a8d423b0317f99e1839. */

import { Show } from "solid-js";

import type { JSX } from "@solidjs/web";

type IconProps = Omit<JSX.SvgSVGAttributes<SVGSVGElement>, "class" | "aria-hidden"> & {
  "aria-hidden"?: "true" | "false";
  class?: string;
  filled?: boolean;
};

function splitIconProps(props: IconProps) {
  const { "aria-hidden": ariaHidden, class: className, filled, ...rest } = props;
  return { ariaHidden, className, filled, rest };
}

export function IconX(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/>
    </svg>
  );
}

export function IconFileText(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M213.66,82.34l-56-56A8,8,0,0,0,152,24H56A16,16,0,0,0,40,40V216a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V88A8,8,0,0,0,213.66,82.34ZM160,51.31,188.69,80H160ZM200,216H56V40h88V88a8,8,0,0,0,8,8h48V216Zm-32-80a8,8,0,0,1-8,8H96a8,8,0,0,1,0-16h64A8,8,0,0,1,168,136Zm0,32a8,8,0,0,1-8,8H96a8,8,0,0,1,0-16h64A8,8,0,0,1,168,168Z"/>
    </svg>
  );
}

export function IconImage(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M216,40H40A16,16,0,0,0,24,56V200a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V56A16,16,0,0,0,216,40Zm0,16V158.75l-26.07-26.06a16,16,0,0,0-22.63,0l-20,20-44-44a16,16,0,0,0-22.62,0L40,149.37V56ZM40,172l52-52,80,80H40Zm176,28H194.63l-36-36,20-20L216,181.38V200ZM144,100a12,12,0,1,1,12,12A12,12,0,0,1,144,100Z"/>
    </svg>
  );
}

export function IconMaskHappy(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M217,34.8a15.94,15.94,0,0,0-14.82-1.71C188.15,38.55,159.82,47.71,128,47.71S67.84,38.55,53.79,33.09A16,16,0,0,0,32,48v55.77c0,35.84,9.65,69.65,27.18,95.18,18.16,26.46,42.6,41,68.82,41s50.66-14.57,68.82-41C214.35,173.44,224,139.63,224,103.79V48A16,16,0,0,0,217,34.8Zm-9,69c0,32.64-8.66,63.23-24.37,86.13C168.54,211.9,148.79,224,128,224s-40.54-12.1-55.63-34.08C56.66,167,48,136.43,48,103.79V48c15.11,5.87,45.58,15.71,80,15.71S192.9,53.87,208,48v55.81Zm-18,18.87A8,8,0,1,1,178,133.33c-2.68-3-8.85-5.33-14-5.33s-11.36,2.34-14,5.33A8,8,0,1,1,138,122.66c5.71-6.38,16.14-10.66,26-10.66S184.25,116.28,190,122.66ZM92,128c-5.19,0-11.36,2.34-14,5.33A8,8,0,1,1,66,122.66C71.75,116.28,82.18,112,92,112s20.25,4.28,26,10.66A8,8,0,1,1,106,133.33C103.36,130.34,97.19,128,92,128Zm76.45,45.19a52.9,52.9,0,0,1-80.9,0A8,8,0,1,1,99.72,162.8a36.89,36.89,0,0,0,56.56,0,8,8,0,0,1,12.17,10.39Z"/>
    </svg>
  );
}

export function IconMicrophone(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,176a48.05,48.05,0,0,0,48-48V64a48,48,0,0,0-96,0v64A48.05,48.05,0,0,0,128,176ZM96,64a32,32,0,0,1,64,0v64a32,32,0,0,1-64,0Zm40,143.6V240a8,8,0,0,1-16,0V207.6A80.11,80.11,0,0,1,48,128a8,8,0,0,1,16,0,64,64,0,0,0,128,0,8,8,0,0,1,16,0A80.11,80.11,0,0,1,136,207.6Z"/>
    </svg>
  );
}

export function IconTrash(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M216,48H176V40a24,24,0,0,0-24-24H104A24,24,0,0,0,80,40v8H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM96,40a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8v8H96Zm96,168H64V64H192ZM112,104v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm48,0v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Z"/>
    </svg>
  );
}

export function IconPencil(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M227.31,73.37,182.63,28.68a16,16,0,0,0-22.63,0L36.69,152A15.86,15.86,0,0,0,32,163.31V208a16,16,0,0,0,16,16H92.69A15.86,15.86,0,0,0,104,219.31L227.31,96a16,16,0,0,0,0-22.63ZM51.31,160,136,75.31,152.69,92,68,176.68ZM48,179.31,76.69,208H48Zm48,25.38L79.31,188,164,103.31,180.69,120Zm96-96L147.31,64l24-24L216,84.68Z"/>
    </svg>
  );
}

export function IconUploadSimple(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,144v64a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V144a8,8,0,0,1,16,0v56H208V144a8,8,0,0,1,16,0ZM93.66,77.66,120,51.31V144a8,8,0,0,0,16,0V51.31l26.34,26.35a8,8,0,0,0,11.32-11.32l-40-40a8,8,0,0,0-11.32,0l-40,40A8,8,0,0,0,93.66,77.66Z"/>
    </svg>
  );
}

export function IconUsersThree(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M244.8,150.4a8,8,0,0,1-11.2-1.6A51.6,51.6,0,0,0,192,128a8,8,0,0,1-7.37-4.89,8,8,0,0,1,0-6.22A8,8,0,0,1,192,112a24,24,0,1,0-23.24-30,8,8,0,1,1-15.5-4A40,40,0,1,1,219,117.51a67.94,67.94,0,0,1,27.43,21.68A8,8,0,0,1,244.8,150.4ZM190.92,212a8,8,0,1,1-13.84,8,57,57,0,0,0-98.16,0,8,8,0,1,1-13.84-8,72.06,72.06,0,0,1,33.74-29.92,48,48,0,1,1,58.36,0A72.06,72.06,0,0,1,190.92,212ZM128,176a32,32,0,1,0-32-32A32,32,0,0,0,128,176ZM72,120a8,8,0,0,0-8-8A24,24,0,1,1,87.24,82a8,8,0,1,0,15.5-4A40,40,0,1,0,37,117.51,67.94,67.94,0,0,0,9.6,139.19a8,8,0,1,0,12.8,9.61A51.6,51.6,0,0,1,64,128,8,8,0,0,0,72,120Z"/>
    </svg>
  );
}

export function IconArrowSquareOut(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,104a8,8,0,0,1-16,0V59.32l-66.33,66.34a8,8,0,0,1-11.32-11.32L196.68,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/>
    </svg>
  );
}

export function IconArrowsClockwise(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,48V96a8,8,0,0,1-8,8H168a8,8,0,0,1,0-16h28.69L182.06,73.37a79.56,79.56,0,0,0-56.13-23.43h-.45A79.52,79.52,0,0,0,69.59,72.71,8,8,0,0,1,58.41,61.27a96,96,0,0,1,135,.79L208,76.69V48a8,8,0,0,1,16,0ZM186.41,183.29a80,80,0,0,1-112.47-.66L59.31,168H88a8,8,0,0,0,0-16H40a8,8,0,0,0-8,8v48a8,8,0,0,0,16,0V179.31l14.63,14.63A95.43,95.43,0,0,0,130,222.06h.53a95.36,95.36,0,0,0,67.07-27.33,8,8,0,0,0-11.18-11.44Z"/>
    </svg>
  );
}

export function IconBroadcast(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,88a40,40,0,1,0,40,40A40,40,0,0,0,128,88Zm0,64a24,24,0,1,1,24-24A24,24,0,0,1,128,152Zm73.71,7.14a80,80,0,0,1-14.08,22.2,8,8,0,0,1-11.92-10.67,63.95,63.95,0,0,0,0-85.33,8,8,0,1,1,11.92-10.67,80.08,80.08,0,0,1,14.08,84.47ZM69,103.09a64,64,0,0,0,11.26,67.58,8,8,0,0,1-11.92,10.67,79.93,79.93,0,0,1,0-106.67A8,8,0,1,1,80.29,85.34,63.77,63.77,0,0,0,69,103.09ZM248,128a119.58,119.58,0,0,1-34.29,84,8,8,0,1,1-11.42-11.2,103.9,103.9,0,0,0,0-145.56A8,8,0,1,1,213.71,44,119.58,119.58,0,0,1,248,128ZM53.71,200.78A8,8,0,1,1,42.29,212a119.87,119.87,0,0,1,0-168,8,8,0,1,1,11.42,11.2,103.9,103.9,0,0,0,0,145.56Z"/>
    </svg>
  );
}

export function IconCalendarBlank(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M208,32H184V24a8,8,0,0,0-16,0v8H88V24a8,8,0,0,0-16,0v8H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM72,48v8a8,8,0,0,0,16,0V48h80v8a8,8,0,0,0,16,0V48h24V80H48V48ZM208,208H48V96H208V208Z"/>
    </svg>
  );
}

export function IconCalendar(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M208,32H184V24a8,8,0,0,0-16,0v8H88V24a8,8,0,0,0-16,0v8H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM72,48v8a8,8,0,0,0,16,0V48h80v8a8,8,0,0,0,16,0V48h24V80H48V48ZM208,208H48V96H208V208Zm-96-88v64a8,8,0,0,1-16,0V132.94l-4.42,2.22a8,8,0,0,1-7.16-14.32l16-8A8,8,0,0,1,112,120Zm59.16,30.45L152,176h16a8,8,0,0,1,0,16H136a8,8,0,0,1-6.4-12.8l28.78-38.37A8,8,0,1,0,145.07,132a8,8,0,1,1-13.85-8A24,24,0,0,1,176,136,23.76,23.76,0,0,1,171.16,150.45Z"/>
    </svg>
  );
}

export function IconCheckCircle(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M173.66,98.34a8,8,0,0,1,0,11.32l-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35A8,8,0,0,1,173.66,98.34ZM232,128A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88,88,0,1,0-88,88A88.1,88.1,0,0,0,216,128Z"/>
    </svg>
  );
}

export function IconClock(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm64-88a8,8,0,0,1-8,8H128a8,8,0,0,1-8-8V72a8,8,0,0,1,16,0v48h48A8,8,0,0,1,192,128Z"/>
    </svg>
  );
}

export function IconCrown(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M248,80a28,28,0,1,0-51.12,15.77l-26.79,33L146,73.4a28,28,0,1,0-36.06,0L85.91,128.74l-26.79-33a28,28,0,1,0-26.6,12L47,194.63A16,16,0,0,0,62.78,208H193.22A16,16,0,0,0,209,194.63l14.47-86.85A28,28,0,0,0,248,80ZM128,40a12,12,0,1,1-12,12A12,12,0,0,1,128,40ZM24,80A12,12,0,1,1,36,92,12,12,0,0,1,24,80ZM193.22,192H62.78L48.86,108.52,81.79,149A8,8,0,0,0,88,152a7.83,7.83,0,0,0,1.08-.07,8,8,0,0,0,6.26-4.74l29.3-67.4a27,27,0,0,0,6.72,0l29.3,67.4a8,8,0,0,0,6.26,4.74A7.83,7.83,0,0,0,168,152a8,8,0,0,0,6.21-3l32.93-40.52ZM220,92a12,12,0,1,1,12-12A12,12,0,0,1,220,92Z"/>
    </svg>
  );
}

export function IconDotsThree(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M140,128a12,12,0,1,1-12-12A12,12,0,0,1,140,128Zm56-12a12,12,0,1,0,12,12A12,12,0,0,0,196,116ZM60,116a12,12,0,1,0,12,12A12,12,0,0,0,60,116Z"/>
    </svg>
  );
}

export function IconDownloadSimple(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,144v64a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V144a8,8,0,0,1,16,0v56H208V144a8,8,0,0,1,16,0Zm-101.66,5.66a8,8,0,0,0,11.32,0l40-40a8,8,0,0,0-11.32-11.32L136,124.69V32a8,8,0,0,0-16,0v92.69L93.66,98.34a8,8,0,0,0-11.32,11.32Z"/>
    </svg>
  );
}

export function IconGlobe(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,24h0A104,104,0,1,0,232,128,104.12,104.12,0,0,0,128,24Zm88,104a87.61,87.61,0,0,1-3.33,24H174.16a157.44,157.44,0,0,0,0-48h38.51A87.61,87.61,0,0,1,216,128ZM102,168H154a115.11,115.11,0,0,1-26,45A115.27,115.27,0,0,1,102,168Zm-3.9-16a140.84,140.84,0,0,1,0-48h59.88a140.84,140.84,0,0,1,0,48ZM40,128a87.61,87.61,0,0,1,3.33-24H81.84a157.44,157.44,0,0,0,0,48H43.33A87.61,87.61,0,0,1,40,128ZM154,88H102a115.11,115.11,0,0,1,26-45A115.27,115.27,0,0,1,154,88Zm52.33,0H170.71a135.28,135.28,0,0,0-22.3-45.6A88.29,88.29,0,0,1,206.37,88ZM107.59,42.4A135.28,135.28,0,0,0,85.29,88H49.63A88.29,88.29,0,0,1,107.59,42.4ZM49.63,168H85.29a135.28,135.28,0,0,0,22.3,45.6A88.29,88.29,0,0,1,49.63,168Zm98.78,45.6a135.28,135.28,0,0,0,22.3-45.6h35.66A88.29,88.29,0,0,1,148.41,213.6Z"/>
    </svg>
  );
}

export function IconInfo(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm16-40a8,8,0,0,1-8,8,16,16,0,0,1-16-16V128a8,8,0,0,1,0-16,16,16,0,0,1,16,16v40A8,8,0,0,1,144,176ZM112,84a12,12,0,1,1,12,12A12,12,0,0,1,112,84Z"/>
    </svg>
  );
}

export function IconLink(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M240,88.23a54.43,54.43,0,0,1-16,37L189.25,160a54.27,54.27,0,0,1-38.63,16h-.05A54.63,54.63,0,0,1,96,119.84a8,8,0,0,1,16,.45A38.62,38.62,0,0,0,150.58,160h0a38.39,38.39,0,0,0,27.31-11.31l34.75-34.75a38.63,38.63,0,0,0-54.63-54.63l-11,11A8,8,0,0,1,135.7,59l11-11A54.65,54.65,0,0,1,224,48,54.86,54.86,0,0,1,240,88.23ZM109,185.66l-11,11A38.41,38.41,0,0,1,70.6,208h0a38.63,38.63,0,0,1-27.29-65.94L78,107.31A38.63,38.63,0,0,1,144,135.71a8,8,0,0,0,16,.45A54.86,54.86,0,0,0,144,96a54.65,54.65,0,0,0-77.27,0L32,130.75A54.62,54.62,0,0,0,70.56,224h0a54.28,54.28,0,0,0,38.64-16l11-11A8,8,0,0,0,109,185.66Z"/>
    </svg>
  );
}

export function IconLock(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M208,80H176V56a48,48,0,0,0-96,0V80H48A16,16,0,0,0,32,96V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V96A16,16,0,0,0,208,80ZM96,56a32,32,0,0,1,64,0V80H96ZM208,208H48V96H208V208Zm-68-56a12,12,0,1,1-12-12A12,12,0,0,1,140,152Z"/>
    </svg>
  );
}

export function IconMapPin(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,64a40,40,0,1,0,40,40A40,40,0,0,0,128,64Zm0,64a24,24,0,1,1,24-24A24,24,0,0,1,128,128Zm0-112a88.1,88.1,0,0,0-88,88c0,31.4,14.51,64.68,42,96.25a254.19,254.19,0,0,0,41.45,38.3,8,8,0,0,0,9.18,0A254.19,254.19,0,0,0,174,200.25c27.45-31.57,42-64.85,42-96.25A88.1,88.1,0,0,0,128,16Zm0,206c-16.53-13-72-60.75-72-118a72,72,0,0,1,144,0C200,161.23,144.53,209,128,222Z"/>
    </svg>
  );
}

export function IconRobot(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M200,48H136V16a8,8,0,0,0-16,0V48H56A32,32,0,0,0,24,80V192a32,32,0,0,0,32,32H200a32,32,0,0,0,32-32V80A32,32,0,0,0,200,48Zm16,144a16,16,0,0,1-16,16H56a16,16,0,0,1-16-16V80A16,16,0,0,1,56,64H200a16,16,0,0,1,16,16Zm-52-56H92a28,28,0,0,0,0,56h72a28,28,0,0,0,0-56Zm-24,16v24H116V152ZM80,164a12,12,0,0,1,12-12h8v24H92A12,12,0,0,1,80,164Zm84,12h-8V152h8a12,12,0,0,1,0,24ZM72,108a12,12,0,1,1,12,12A12,12,0,0,1,72,108Zm88,0a12,12,0,1,1,12,12A12,12,0,0,1,160,108Z"/>
    </svg>
  );
}

export function IconShareFat(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M237.66,106.35l-80-80A8,8,0,0,0,144,32V72.35c-25.94,2.22-54.59,14.92-78.16,34.91-28.38,24.08-46.05,55.11-49.76,87.37a12,12,0,0,0,20.68,9.58h0c11-11.71,50.14-48.74,107.24-52V192a8,8,0,0,0,13.66,5.65l80-80A8,8,0,0,0,237.66,106.35ZM160,172.69V144a8,8,0,0,0-8-8c-28.08,0-55.43,7.33-81.29,21.8a196.17,196.17,0,0,0-36.57,26.52c5.8-23.84,20.42-46.51,42.05-64.86C99.41,99.77,127.75,88,152,88a8,8,0,0,0,8-8V51.32L220.69,112Z"/>
    </svg>
  );
}

export function IconShareNetwork(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M176,160a39.89,39.89,0,0,0-28.62,12.09l-46.1-29.63a39.8,39.8,0,0,0,0-28.92l46.1-29.63a40,40,0,1,0-8.66-13.45l-46.1,29.63a40,40,0,1,0,0,55.82l46.1,29.63A40,40,0,1,0,176,160Zm0-128a24,24,0,1,1-24,24A24,24,0,0,1,176,32ZM64,152a24,24,0,1,1,24-24A24,24,0,0,1,64,152Zm112,72a24,24,0,1,1,24-24A24,24,0,0,1,176,224Z"/>
    </svg>
  );
}

export function IconShield(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M208,40H48A16,16,0,0,0,32,56v56c0,52.72,25.52,84.67,46.93,102.19,23.06,18.86,46,25.27,47,25.53a8,8,0,0,0,4.2,0c1-.26,23.91-6.67,47-25.53C198.48,196.67,224,164.72,224,112V56A16,16,0,0,0,208,40Zm0,72c0,37.07-13.66,67.16-40.6,89.42A129.3,129.3,0,0,1,128,223.62a128.25,128.25,0,0,1-38.92-21.81C61.82,179.51,48,149.3,48,112l0-56,160,0Z"/>
    </svg>
  );
}

export function IconUsers(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M117.25,157.92a60,60,0,1,0-66.5,0A95.83,95.83,0,0,0,3.53,195.63a8,8,0,1,0,13.4,8.74,80,80,0,0,1,134.14,0,8,8,0,0,0,13.4-8.74A95.83,95.83,0,0,0,117.25,157.92ZM40,108a44,44,0,1,1,44,44A44.05,44.05,0,0,1,40,108Zm210.14,98.7a8,8,0,0,1-11.07-2.33A79.83,79.83,0,0,0,172,168a8,8,0,0,1,0-16,44,44,0,1,0-16.34-84.87,8,8,0,1,1-5.94-14.85,60,60,0,0,1,55.53,105.64,95.83,95.83,0,0,1,47.22,37.71A8,8,0,0,1,250.14,206.7Z"/>
    </svg>
  );
}

export function IconVideoCamera(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M251.77,73a8,8,0,0,0-8.21.39L208,97.05V72a16,16,0,0,0-16-16H32A16,16,0,0,0,16,72V184a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V159l35.56,23.71A8,8,0,0,0,248,184a8,8,0,0,0,8-8V80A8,8,0,0,0,251.77,73ZM192,184H32V72H192V184Zm48-22.95-32-21.33V116.28L240,95Z"/>
    </svg>
  );
}

export function IconVinylRecord(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm0-144a56.06,56.06,0,0,0-56,56,8,8,0,0,1-16,0,72.08,72.08,0,0,1,72-72,8,8,0,0,1,0,16Zm72,56a72.08,72.08,0,0,1-72,72,8,8,0,0,1,0-16,56.06,56.06,0,0,0,56-56,8,8,0,0,1,16,0Zm-40,0a32,32,0,1,0-32,32A32,32,0,0,0,160,128Zm-48,0a16,16,0,1,1,16,16A16,16,0,0,1,112,128Z"/>
    </svg>
  );
}

export function IconWarningCircle(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm-8-80V80a8,8,0,0,1,16,0v56a8,8,0,0,1-16,0Zm20,36a12,12,0,1,1-12-12A12,12,0,0,1,140,172Z"/>
    </svg>
  );
}

export function IconCheck(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z"/>
    </svg>
  );
}

export function IconArrowUp(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M205.66,117.66a8,8,0,0,1-11.32,0L136,59.31V216a8,8,0,0,1-16,0V59.31L61.66,117.66a8,8,0,0,1-11.32-11.32l72-72a8,8,0,0,1,11.32,0l72,72A8,8,0,0,1,205.66,117.66Z"/>
    </svg>
  );
}

export function IconArrowDown(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M205.66,149.66l-72,72a8,8,0,0,1-11.32,0l-72-72a8,8,0,0,1,11.32-11.32L120,196.69V40a8,8,0,0,1,16,0V196.69l58.34-58.35a8,8,0,0,1,11.32,11.32Z"/>
    </svg>
  );
}

export function IconChatCircle(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M128,24A104,104,0,0,0,36.18,176.88L24.83,210.93a16,16,0,0,0,20.24,20.24l34.05-11.35A104,104,0,1,0,128,24Zm0,192a87.87,87.87,0,0,1-44.06-11.81,8,8,0,0,0-6.54-.67L40,216,52.47,178.6a8,8,0,0,0-.66-6.54A88,88,0,1,1,128,216Z"/>
          </>
        }
      >
        <>
          <path d="M232,128A104,104,0,0,1,79.12,219.82L45.07,231.17a16,16,0,0,1-20.24-20.24l11.35-34.05A104,104,0,1,1,232,128Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconPlay(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M232.4,114.49,88.32,26.35a16,16,0,0,0-16.2-.3A15.86,15.86,0,0,0,64,39.87V216.13A15.94,15.94,0,0,0,80,232a16.07,16.07,0,0,0,8.36-2.35L232.4,141.51a15.81,15.81,0,0,0,0-27ZM80,215.94V40l143.83,88Z"/>
          </>
        }
      >
        <>
          <path d="M240,128a15.74,15.74,0,0,1-7.6,13.51L88.32,229.65a16,16,0,0,1-16.2.3A15.86,15.86,0,0,1,64,216.13V39.87a15.86,15.86,0,0,1,8.12-13.82,16,16,0,0,1,16.2.3L232.4,114.49A15.74,15.74,0,0,1,240,128Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconPause(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M200,32H160a16,16,0,0,0-16,16V208a16,16,0,0,0,16,16h40a16,16,0,0,0,16-16V48A16,16,0,0,0,200,32Zm0,176H160V48h40ZM96,32H56A16,16,0,0,0,40,48V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V48A16,16,0,0,0,96,32Zm0,176H56V48H96Z"/>
    </svg>
  );
}

export function IconCircleNotch(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M232,128a104,104,0,0,1-208,0c0-41,23.81-78.36,60.66-95.27a8,8,0,0,1,6.68,14.54C60.15,61.59,40,93.27,40,128a88,88,0,0,0,176,0c0-34.73-20.15-66.41-51.34-80.73a8,8,0,0,1,6.68-14.54C208.19,49.64,232,87,232,128Z"/>
    </svg>
  );
}

export function IconMusicNote(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M210.3,56.34l-80-24A8,8,0,0,0,120,40V148.26A48,48,0,1,0,136,184V98.75l69.7,20.91A8,8,0,0,0,216,112V64A8,8,0,0,0,210.3,56.34ZM88,216a32,32,0,1,1,32-32A32,32,0,0,1,88,216ZM200,101.25l-64-19.2V50.75L200,70Z"/>
    </svg>
  );
}

export function IconCopy(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M216,32H88a8,8,0,0,0-8,8V80H40a8,8,0,0,0-8,8V216a8,8,0,0,0,8,8H168a8,8,0,0,0,8-8V176h40a8,8,0,0,0,8-8V40A8,8,0,0,0,216,32ZM160,208H48V96H160Zm48-48H176V88a8,8,0,0,0-8-8H96V48H208Z"/>
    </svg>
  );
}

export function IconCaretDown(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"/>
    </svg>
  );
}

export function IconCaretLeft(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M165.66,202.34a8,8,0,0,1-11.32,11.32l-80-80a8,8,0,0,1,0-11.32l80-80a8,8,0,0,1,11.32,11.32L91.31,128Z"/>
    </svg>
  );
}

export function IconCaretRight(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M181.66,133.66l-80,80a8,8,0,0,1-11.32-11.32L164.69,128,90.34,53.66a8,8,0,0,1,11.32-11.32l80,80A8,8,0,0,1,181.66,133.66Z"/>
    </svg>
  );
}

export function IconArrowLeft(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,128a8,8,0,0,1-8,8H59.31l58.35,58.34a8,8,0,0,1-11.32,11.32l-72-72a8,8,0,0,1,0-11.32l72-72a8,8,0,0,1,11.32,11.32L59.31,120H216A8,8,0,0,1,224,128Z"/>
    </svg>
  );
}

export function IconArrowRight(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M221.66,133.66l-72,72a8,8,0,0,1-11.32-11.32L196.69,136H40a8,8,0,0,1,0-16H196.69L138.34,61.66a8,8,0,0,1,11.32-11.32l72,72A8,8,0,0,1,221.66,133.66Z"/>
    </svg>
  );
}

export function IconHouse(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M219.31,108.68l-80-80a16,16,0,0,0-22.62,0l-80,80A15.87,15.87,0,0,0,32,120v96a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V160h32v56a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V120A15.87,15.87,0,0,0,219.31,108.68ZM208,208H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48V120l80-80,80,80Z"/>
          </>
        }
      >
        <>
          <path d="M224,120v96a8,8,0,0,1-8,8H160a8,8,0,0,1-8-8V164a4,4,0,0,0-4-4H108a4,4,0,0,0-4,4v52a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V120a16,16,0,0,1,4.69-11.31l80-80a16,16,0,0,1,22.62,0l80,80A16,16,0,0,1,224,120Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconBell(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M221.8,175.94C216.25,166.38,208,139.33,208,104a80,80,0,1,0-160,0c0,35.34-8.26,62.38-13.81,71.94A16,16,0,0,0,48,200H88.81a40,40,0,0,0,78.38,0H208a16,16,0,0,0,13.8-24.06ZM128,216a24,24,0,0,1-22.62-16h45.24A24,24,0,0,1,128,216ZM48,184c7.7-13.24,16-43.92,16-80a64,64,0,1,1,128,0c0,36.05,8.28,66.73,16,80Z"/>
          </>
        }
      >
        <>
          <path d="M221.8,175.94C216.25,166.38,208,139.33,208,104a80,80,0,1,0-160,0c0,35.34-8.26,62.38-13.81,71.94A16,16,0,0,0,48,200H88.81a40,40,0,0,0,78.38,0H208a16,16,0,0,0,13.8-24.06ZM128,216a24,24,0,0,1-22.62-16h45.24A24,24,0,0,1,128,216Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconWallet(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M216,64H56a8,8,0,0,1,0-16H192a8,8,0,0,0,0-16H56A24,24,0,0,0,32,56V184a24,24,0,0,0,24,24H216a16,16,0,0,0,16-16V80A16,16,0,0,0,216,64Zm0,128H56a8,8,0,0,1-8-8V78.63A23.84,23.84,0,0,0,56,80H216Zm-48-60a12,12,0,1,1,12,12A12,12,0,0,1,168,132Z"/>
          </>
        }
      >
        <>
          <path d="M216,64H56a8,8,0,0,1,0-16H192a8,8,0,0,0,0-16H56A24,24,0,0,0,32,56V184a24,24,0,0,0,24,24H216a16,16,0,0,0,16-16V80A16,16,0,0,0,216,64Zm-36,80a12,12,0,1,1,12-12A12,12,0,0,1,180,144Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconPlaylist(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M32,64a8,8,0,0,1,8-8H216a8,8,0,0,1,0,16H40A8,8,0,0,1,32,64Zm8,72H160a8,8,0,0,0,0-16H40a8,8,0,0,0,0,16Zm72,48H40a8,8,0,0,0,0,16h72a8,8,0,0,0,0-16Zm135.66-57.7a8,8,0,0,1-10,5.36L208,122.75V192a32.05,32.05,0,1,1-16-27.69V112a8,8,0,0,1,10.3-7.66l40,12A8,8,0,0,1,247.66,126.3ZM192,192a16,16,0,1,0-16,16A16,16,0,0,0,192,192Z"/>
          </>
        }
      >
        <>
          <path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM64,72H192a8,8,0,0,1,0,16H64a8,8,0,0,1,0-16Zm0,48h72a8,8,0,0,1,0,16H64a8,8,0,0,1,0-16Zm40,64H64a8,8,0,0,1,0-16h40a8,8,0,0,1,0,16Zm103.59-53.47a8,8,0,0,1-10.12,5.06L184,131.1V176a24,24,0,1,1-16-22.62V120a8,8,0,0,1,10.53-7.59l24,8A8,8,0,0,1,207.59,130.53Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconHandPalm(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M188,88a27.75,27.75,0,0,0-12,2.71V60a28,28,0,0,0-41.36-24.6A28,28,0,0,0,80,44v6.71A27.75,27.75,0,0,0,68,48,28,28,0,0,0,40,76v76a88,88,0,0,0,176,0V116A28,28,0,0,0,188,88Zm12,64a72,72,0,0,1-144,0V76a12,12,0,0,1,24,0v44a8,8,0,0,0,16,0V44a12,12,0,0,1,24,0v68a8,8,0,0,0,16,0V60a12,12,0,0,1,24,0v68.67A48.08,48.08,0,0,0,120,176a8,8,0,0,0,16,0,32,32,0,0,1,32-32,8,8,0,0,0,8-8V116a12,12,0,0,1,24,0Z"/>
    </svg>
  );
}

export function IconMicrophoneStage(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M168,16A72.07,72.07,0,0,0,96,88a73.29,73.29,0,0,0,.63,9.42L27.12,192.22A15.93,15.93,0,0,0,28.71,213L43,227.29a15.93,15.93,0,0,0,20.78,1.59l94.81-69.53A73.29,73.29,0,0,0,168,160a72,72,0,1,0,0-144Zm56,72a55.72,55.72,0,0,1-11.16,33.52L134.49,43.16A56,56,0,0,1,224,88ZM54.32,216,40,201.68,102.14,117A72.37,72.37,0,0,0,139,153.86ZM112,88a55.67,55.67,0,0,1,11.16-33.51l78.34,78.34A56,56,0,0,1,112,88Zm-2.35,58.34a8,8,0,0,1,0,11.31l-8,8a8,8,0,1,1-11.31-11.31l8-8A8,8,0,0,1,109.67,146.33Z"/>
          </>
        }
      >
        <>
          <path d="M115.06,46.36a4,4,0,0,0-6.11.54A71.54,71.54,0,0,0,96,88a73.29,73.29,0,0,0,.63,9.42L27.12,192.22A15.93,15.93,0,0,0,28.71,213L43,227.29a15.93,15.93,0,0,0,20.78,1.59l94.81-69.53A73.29,73.29,0,0,0,168,160a71.54,71.54,0,0,0,41.09-12.93,4,4,0,0,0,.54-6.11Zm2.61,103.28-16,16a8,8,0,1,1-11.31-11.31l16-16a8,8,0,0,1,11.31,11.31Zm109.4-20.56a4,4,0,0,1-6.12.54L126.38,35.05a4,4,0,0,1,.54-6.12A71.93,71.93,0,0,1,227.07,129.08Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconArrowCounterClockwise(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,128a96,96,0,0,1-94.71,96H128A95.38,95.38,0,0,1,62.1,197.8a8,8,0,0,1,11-11.63A80,80,0,1,0,71.43,71.39a3.07,3.07,0,0,1-.26.25L44.59,96H72a8,8,0,0,1,0,16H24a8,8,0,0,1-8-8V56a8,8,0,0,1,16,0V85.8L60.25,60A96,96,0,0,1,224,128Z"/>
    </svg>
  );
}

export function IconGift(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M216,72H180.92c.39-.33.79-.65,1.17-1A29.53,29.53,0,0,0,192,49.57,32.62,32.62,0,0,0,158.44,16,29.53,29.53,0,0,0,137,25.91a54.94,54.94,0,0,0-9,14.48,54.94,54.94,0,0,0-9-14.48A29.53,29.53,0,0,0,97.56,16,32.62,32.62,0,0,0,64,49.57,29.53,29.53,0,0,0,73.91,71c.38.33.78.65,1.17,1H40A16,16,0,0,0,24,88v32a16,16,0,0,0,16,16v64a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V136a16,16,0,0,0,16-16V88A16,16,0,0,0,216,72ZM149,36.51a13.69,13.69,0,0,1,10-4.5h.49A16.62,16.62,0,0,1,176,49.08a13.69,13.69,0,0,1-4.5,10c-9.49,8.4-25.24,11.36-35,12.4C137.7,60.89,141,45.5,149,36.51Zm-64.09.36A16.63,16.63,0,0,1,96.59,32h.49a13.69,13.69,0,0,1,10,4.5c8.39,9.48,11.35,25.2,12.39,34.92-9.72-1-25.44-4-34.92-12.39a13.69,13.69,0,0,1-4.5-10A16.6,16.6,0,0,1,84.87,36.87ZM40,88h80v32H40Zm16,48h64v64H56Zm144,64H136V136h64Zm16-80H136V88h80v32Z"/>
          </>
        }
      >
        <>
          <path d="M216,72H180.92c.39-.33.79-.65,1.17-1A29.53,29.53,0,0,0,192,49.57,32.62,32.62,0,0,0,158.44,16,29.53,29.53,0,0,0,137,25.91a54.94,54.94,0,0,0-9,14.48,54.94,54.94,0,0,0-9-14.48A29.53,29.53,0,0,0,97.56,16,32.62,32.62,0,0,0,64,49.57,29.53,29.53,0,0,0,73.91,71c.38.33.78.65,1.17,1H40A16,16,0,0,0,24,88v32a16,16,0,0,0,16,16v64a16,16,0,0,0,16,16h60a4,4,0,0,0,4-4V120H40V88h80v32h16V88h80v32H136v92a4,4,0,0,0,4,4h60a16,16,0,0,0,16-16V136a16,16,0,0,0,16-16V88A16,16,0,0,0,216,72ZM84.51,59a13.69,13.69,0,0,1-4.5-10A16.62,16.62,0,0,1,96.59,32h.49a13.69,13.69,0,0,1,10,4.5c8.39,9.48,11.35,25.2,12.39,34.92C109.71,70.39,94,67.43,84.51,59Zm87,0c-9.49,8.4-25.24,11.36-35,12.4C137.7,60.89,141,45.5,149,36.51a13.69,13.69,0,0,1,10-4.5h.49A16.62,16.62,0,0,1,176,49.08,13.69,13.69,0,0,1,171.49,59Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconPlus(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z"/>
    </svg>
  );
}

export function IconList(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM40,72H216a8,8,0,0,0,0-16H40a8,8,0,0,0,0,16ZM216,184H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z"/>
    </svg>
  );
}

export function IconSquare(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32Zm0,176H48V48H208V208Z"/>
    </svg>
  );
}

export function IconStop(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M216,56V200a16,16,0,0,1-16,16H56a16,16,0,0,1-16-16V56A16,16,0,0,1,56,40H200A16,16,0,0,1,216,56Z"/>
    </svg>
  );
}

export function IconSidebarSimple(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M216,40H40A16,16,0,0,0,24,56V200a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V56A16,16,0,0,0,216,40ZM40,56H80V200H40ZM216,200H96V56H216V200Z"/>
    </svg>
  );
}

export function IconFire(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <Show
        when={iconProps.filled}
        fallback={
          <>
            <path d="M183.89,153.34a57.6,57.6,0,0,1-46.56,46.55A8.75,8.75,0,0,1,136,200a8,8,0,0,1-1.32-15.89c16.57-2.79,30.63-16.85,33.44-33.45a8,8,0,0,1,15.78,2.68ZM216,144a88,88,0,0,1-176,0c0-27.92,11-56.47,32.66-84.85a8,8,0,0,1,11.93-.89l24.12,23.41,22-60.41a8,8,0,0,1,12.63-3.41C165.21,36,216,84.55,216,144Zm-16,0c0-46.09-35.79-85.92-58.21-106.33L119.52,98.74a8,8,0,0,1-13.09,3L80.06,76.16C64.09,99.21,56,122,56,144a72,72,0,0,0,144,0Z"/>
          </>
        }
      >
        <>
          <path d="M143.38,17.85a8,8,0,0,0-12.63,3.41l-22,60.41L84.59,58.26a8,8,0,0,0-11.93.89C51,87.53,40,116.08,40,144a88,88,0,0,0,176,0C216,84.55,165.21,36,143.38,17.85Zm40.51,135.49a57.6,57.6,0,0,1-46.56,46.55A7.65,7.65,0,0,1,136,200a8,8,0,0,1-1.32-15.89c16.57-2.79,30.63-16.85,33.44-33.45a8,8,0,0,1,15.78,2.68Z"/>
        </>
      </Show>
    </svg>
  );
}

export function IconFlag(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M42.76,50A8,8,0,0,0,40,56V224a8,8,0,0,0,16,0V179.77c26.79-21.16,49.87-9.75,76.45,3.41,16.4,8.11,34.06,16.85,53,16.85,13.93,0,28.54-4.75,43.82-18a8,8,0,0,0,2.76-6V56A8,8,0,0,0,218.76,50c-28,24.23-51.72,12.49-79.21-1.12C111.07,34.76,78.78,18.79,42.76,50ZM216,172.25c-26.79,21.16-49.87,9.74-76.45-3.41-25-12.35-52.81-26.13-83.55-8.4V59.79c26.79-21.16,49.87-9.75,76.45,3.4,25,12.35,52.82,26.13,83.55,8.4Z"/>
    </svg>
  );
}

export function IconMagnifyingGlass(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z"/>
    </svg>
  );
}

export function IconTrendUp(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M240,56v64a8,8,0,0,1-16,0V75.31l-82.34,82.35a8,8,0,0,1-11.32,0L96,123.31,29.66,189.66a8,8,0,0,1-11.32-11.32l72-72a8,8,0,0,1,11.32,0L136,140.69,212.69,64H168a8,8,0,0,1,0-16h64A8,8,0,0,1,240,56Z"/>
    </svg>
  );
}

export function IconQuote(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M100,56H40A16,16,0,0,0,24,72v64a16,16,0,0,0,16,16h60v8a32,32,0,0,1-32,32,8,8,0,0,0,0,16,48.05,48.05,0,0,0,48-48V72A16,16,0,0,0,100,56Zm0,80H40V72h60ZM216,56H156a16,16,0,0,0-16,16v64a16,16,0,0,0,16,16h60v8a32,32,0,0,1-32,32,8,8,0,0,0,0,16,48.05,48.05,0,0,0,48-48V72A16,16,0,0,0,216,56Zm0,80H156V72h60Z"/>
    </svg>
  );
}

export function IconLinkSimple(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M165.66,90.34a8,8,0,0,1,0,11.32l-64,64a8,8,0,0,1-11.32-11.32l64-64A8,8,0,0,1,165.66,90.34ZM215.6,40.4a56,56,0,0,0-79.2,0L106.34,70.45a8,8,0,0,0,11.32,11.32l30.06-30a40,40,0,0,1,56.57,56.56l-30.07,30.06a8,8,0,0,0,11.31,11.32L215.6,119.6a56,56,0,0,0,0-79.2ZM138.34,174.22l-30.06,30.06a40,40,0,1,1-56.56-56.57l30.05-30.05a8,8,0,0,0-11.32-11.32L40.4,136.4a56,56,0,0,0,79.2,79.2l30.06-30.07a8,8,0,0,0-11.32-11.31Z"/>
    </svg>
  );
}

export function IconListBullets(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M80,64a8,8,0,0,1,8-8H216a8,8,0,0,1,0,16H88A8,8,0,0,1,80,64Zm136,56H88a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Zm0,64H88a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16ZM44,52A12,12,0,1,0,56,64,12,12,0,0,0,44,52Zm0,64a12,12,0,1,0,12,12A12,12,0,0,0,44,116Zm0,64a12,12,0,1,0,12,12A12,12,0,0,0,44,180Z"/>
    </svg>
  );
}

export function IconListNumbers(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M224,128a8,8,0,0,1-8,8H104a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128ZM104,72H216a8,8,0,0,0,0-16H104a8,8,0,0,0,0,16ZM216,184H104a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16ZM43.58,55.16,48,52.94V104a8,8,0,0,0,16,0V40a8,8,0,0,0-11.58-7.16l-16,8a8,8,0,0,0,7.16,14.32ZM79.77,156.72a23.73,23.73,0,0,0-9.6-15.95,24.86,24.86,0,0,0-34.11,4.7,23.63,23.63,0,0,0-3.57,6.46,8,8,0,1,0,15,5.47,7.84,7.84,0,0,1,1.18-2.13,8.76,8.76,0,0,1,12-1.59A7.91,7.91,0,0,1,63.93,159a7.64,7.64,0,0,1-1.57,5.78,1,1,0,0,0-.08.11L33.59,203.21A8,8,0,0,0,40,216H72a8,8,0,0,0,0-16H56l19.08-25.53A23.47,23.47,0,0,0,79.77,156.72Z"/>
    </svg>
  );
}

export function IconSpeakerHigh(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M155.51,24.81a8,8,0,0,0-8.42.88L77.25,80H32A16,16,0,0,0,16,96v64a16,16,0,0,0,16,16H77.25l69.84,54.31A8,8,0,0,0,160,224V32A8,8,0,0,0,155.51,24.81ZM32,96H72v64H32ZM144,207.64,88,164.09V91.91l56-43.55Zm54-106.08a40,40,0,0,1,0,52.88,8,8,0,0,1-12-10.58,24,24,0,0,0,0-31.72,8,8,0,0,1,12-10.58ZM248,128a79.9,79.9,0,0,1-20.37,53.34,8,8,0,0,1-11.92-10.67,64,64,0,0,0,0-85.33,8,8,0,1,1,11.92-10.67A79.83,79.83,0,0,1,248,128Z"/>
    </svg>
  );
}

export function IconSpeakerSlash(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M53.92,34.62A8,8,0,1,0,42.08,45.38L73.55,80H32A16,16,0,0,0,16,96v64a16,16,0,0,0,16,16H77.25l69.84,54.31A8,8,0,0,0,160,224V175.09l42.08,46.29a8,8,0,1,0,11.84-10.76ZM32,96H72v64H32ZM144,207.64,88,164.09V95.89l56,61.6Zm42-63.77a24,24,0,0,0,0-31.72,8,8,0,1,1,12-10.57,40,40,0,0,1,0,52.88,8,8,0,0,1-12-10.59Zm-80.16-76a8,8,0,0,1,1.4-11.23l39.85-31A8,8,0,0,1,160,32v74.83a8,8,0,0,1-16,0V48.36l-26.94,21A8,8,0,0,1,105.84,67.91ZM248,128a79.9,79.9,0,0,1-20.37,53.34,8,8,0,0,1-11.92-10.67,64,64,0,0,0,0-85.33,8,8,0,1,1,11.92-10.67A79.83,79.83,0,0,1,248,128Z"/>
    </svg>
  );
}

export function IconHeart(props: IconProps) {
  const iconProps = splitIconProps(props);
  return (
    <svg aria-hidden={iconProps.ariaHidden ?? "true"} class={iconProps.className} fill="currentColor" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" {...iconProps.rest}>
      <path d="M240,102c0,70-103.79,126.66-108.21,129a8,8,0,0,1-7.58,0C119.79,228.66,16,172,16,102A62.07,62.07,0,0,1,78,40c20.65,0,38.73,8.88,50,23.89C139.27,48.88,157.35,40,178,40A62.07,62.07,0,0,1,240,102Z"/>
    </svg>
  );
}
