import path from "node:path";
import { availableParallelism } from "node:os";
import { defineConfig } from "vitest/config";
import tailwindcss from "@tailwindcss/vite";
import solid from "@solidjs/vite-plugin";

const solidUiRoot = path.resolve(import.meta.dirname, "packages/solid-ui");

export default defineConfig({
  plugins: [tailwindcss(), solid({ ssr: false })],
  resolve: {
    dedupe: ["solid-js", "@solidjs/web"],
    alias: {
      "@": path.resolve(solidUiRoot, "src"),
      "solid-js/web": "@solidjs/web",
    },
  },
  test: {
    name: "app-components",
    environment: "jsdom",
    // Each file owns a jsdom environment and a transformed Solid graph. The
    // The default CPU-sized pool can exhaust memory on large runners. Never
    // oversubscribe smaller CI guests, where extra jsdom workers instead
    // starve interaction timers.
    maxWorkers: Math.min(4, availableParallelism()),
    // The app still has Bun-native .tsx suites; they are intentionally not
    // loaded by Vitest. Add a suite here once it imports Vitest's API, and
    // keep scripts/check-test-discovery.ts green when ownership moves.
    include: [
      "src/features/posts/song-player/song-player.test.tsx",
      "src/features/rewards/*.test.ts",
      "src/features/rewards/*.test.tsx",
      "src/hns-community-route-transform.test.ts",
      "src/lib/viewer-session-hint.test.ts",
      "src/routes/community-owner-settings-route.test.ts",
      "src/routes/community-route-filesystem.test.ts",
      "src/features/posts/public-post/public-post-route.model.test.ts",
      "src/features/posts/public-post/public-post-preflight.test.ts",
      "src/features/posts/public-post/public-post-route-view.test.tsx",
      "src/features/posts/public-post/song-published-status.test.ts",
      "src/features/posts/public-post/song-video-entry.test.tsx",
      "src/features/posts/song-attribution/song-attribution.test.ts",
      "src/features/posts/song-attribution/song-attribution-chip.test.tsx",
      "src/features/posts/public-post/public-post-sitemap.test.ts",
      "src/routes/index.test.tsx",
      "src/routes/legal-routes.test.tsx",
      "src/features/auth/global-sign-in-host.test.tsx",
      "src/features/auth/sign-in-model.test.ts",
      "src/features/auth/sign-in-preparation.test.ts",
      "src/features/auth/sign-in-return.test.ts",
      "src/features/auth/sign-in-session.test.ts",
      "src/features/auth/sign-in-view.test.tsx",
      "src/features/community/community-creation-api.test.ts",
      "src/features/community/community-creation-avatar-authoring.test.ts",
      "src/features/community/create-community/create-community-model.test.ts",
      "src/features/community/page-shell/page-shell-actions.test.tsx",
      "src/features/community/community-creation-route-view.test.tsx",
      "src/features/community/your-communities-page/your-communities-route.test.tsx",
      "src/features/community/owner-settings/community-names-settings-api.test.ts",
      "src/features/community/owner-settings/community-names-settings-controller.test.tsx",
      "src/features/community/owner-settings/community-names-settings-model.test.ts",
      "src/features/community/owner-settings/community-moderation-settings-api.test.ts",
      "src/features/community/owner-settings/community-moderation-settings-controller.test.tsx",
      "src/features/community/owner-settings/community-moderation-settings-model.test.ts",
      "src/features/community/owner-settings/community-management-shell.test.tsx",
      "src/features/community/owner-settings/community-hns-wallet.test.ts",
      "src/features/community/owner-settings/community-namespace-settings-api.test.ts",
      "src/features/community/owner-settings/community-namespace-settings-controller.test.tsx",
      "src/features/community/owner-settings/community-namespace-admission.test.tsx",
      "src/features/community/owner-settings/community-namespace-lifecycle.test.tsx",
      "src/features/community/owner-settings/community-namespace-failure-reference.test.tsx",
      "src/features/community/owner-settings/owner-settings-model.test.ts",
      "src/features/community/owner-settings/owner-settings-route-model.test.ts",
      "src/features/community/owner-settings/owner-settings-route-view.test.tsx",
      "src/features/communities/community-page/community-page.model.test.ts",
      "src/features/communities/community-page/community-engagement-api.test.ts",
      "src/features/communities/community-page/community-engagement-controller.test.tsx",
      "src/features/communities/community-page/community-identity-transitions.test.tsx",
      "src/features/communities/community-page/community-page-pending-geometry.test.tsx",
      "src/features/communities/community-page/community-page.test.tsx",
      "src/features/communities/community-page/community-thread-feed-api.test.ts",
    "src/features/communities/community-page/community-viewer-vote-api.test.ts",
      "src/features/communities/handle-storefront/handle-storefront.flow.test.ts",
      "src/features/communities/handle-storefront/handle-storefront.model.test.ts",
      "src/features/communities/handle-storefront/handle-storefront.test.tsx",
      "src/features/karaoke/karaoke-api.test.ts",
      "src/features/karaoke/karaoke-route-view.test.tsx",
      "src/features/identity/activity-persona-preparation.test.ts",
      "src/features/identity/community-persona-choice-sheet.test.tsx",
      "src/features/identity/community-persona-choice.test.ts",
      "src/features/posts/feed/public-feed.test.tsx",
      "src/features/posts/feed/public-feed.test.ts",
      "src/features/posts/video-feed/home-feed-study.test.ts",
      "src/features/posts/video-feed/home-video-feed.test.tsx",
      "src/features/posts/feed/public-feed-song-reference.test.ts",
      "src/features/posts/post-engagement/post-engagement-api.test.ts",
      "src/features/posts/post-engagement/post-engagement-model.test.ts",
      "src/features/posts/post-engagement/post-engagement-pending.test.ts",
      "src/features/posts/post-engagement/post-engagement.test.tsx",
      "src/features/posts/post-composer/capability-boundary.test.tsx",
      "src/features/posts/post-composer/create-post-dialog.test.tsx",
      "src/features/posts/post-composer/post-composer-submission.test.tsx",
      "src/features/posts/post-composer/video-original-audio-surface.test.tsx",
      "src/features/posts/media-submission/coordinator.test.ts",
      "src/features/posts/video-submission/multipart.test.ts",
      "src/features/posts/video-submission/coordinator.test.ts",
      "src/features/posts/video-submission/capture.test.ts",
      "src/features/posts/video-submission/delivery-state.test.ts",
      "src/features/posts/video-submission/playback-access.test.ts",
      "src/features/posts/video-submission/video-player.test.tsx",
      "src/features/posts/video-submission/video-composer-runtime.test.tsx",
      "src/features/posts/video-submission/song-reference.test.ts",
      "src/features/posts/video-submission/clip-duration.test.ts",
      "src/features/posts/video-submission/song-review-preview.test.tsx",
      "src/features/posts/post-composer/song-excerpt.test.ts",
      "src/features/posts/post-composer/song-excerpt-draft.test.ts",
      "src/features/posts/post-composer/song-excerpt-link.test.ts",
      "src/features/posts/post-composer/text-submission-contract.test.ts",
      "src/features/posts/post-composer/pending-submission.test.ts",
      "src/features/posts/post-composer/text-submission-transport.test.ts",
      "src/features/profiles/public-profile-page/public-profile-page.test.tsx",
      "src/features/profiles/persona-public-profile/persona-public-profile.test.tsx",
      "src/features/shell/media-shell/media-shell.test.tsx",
      "src/features/shell/application-chrome-model.test.ts",
      "src/features/studying/study-session-start-coordinator.test.ts",
      "src/features/shell/application-personas.test.ts",
      "src/features/songs/your-songs-model.test.ts",
      "src/features/wallet/wallet-portfolio.test.tsx",
      "src/features/wallet/wallet-balances.test.ts",
      "src/features/wallet/wallet-balance-reader.test.ts",
      "src/features/wallet/wallet-hub-model.test.ts",
      "src/features/wallet/wallet-hub-view-model.test.ts",
      "src/features/wallet/wallet-receive-sheet-model.test.ts",
      "src/features/wallet/wallet-receive-sheet-view-model.test.ts",
      "src/features/studying/study-v2-api.test.ts",
      "src/features/studying/study-v2-route-view.test.tsx",
      "src/features/studying/study-v2-runtime-client.test.ts",
      "src/features/studying/studying-browser-recorder.test.ts",
      "src/middleware.test.ts",
      "src/routes/verify/very.test.tsx",
      "src/routes/verify/zkpassport.test.tsx",
      "src/features/verification/document-verification-host.test.tsx",
      "src/features/verification/age-verification.test.ts",
      "src/features/posts/post-engagement/comment-thread-controller.test.ts",
    ],
  },
});
