// Generated by scripts/hns-public-persona-validator.py --write.
// The algorithm below is byte-identical to the reviewed client implementation.
/* oxlint-disable anti-slop/no-unsafe-dictionary-type -- This frozen generated algorithm validates unknown JSON at the wire boundary. */
import { publicPersonaSchema } from "./public-persona-schema.ts";
import type { GetPublicPersonasPersonaIdResponse } from "@pirate/api-client";
type JsonSchema = Record<string, unknown>;
function record(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function schemaError(value: unknown, schema: JsonSchema, path: string, root: JsonSchema): string | undefined {
  if (typeof schema.$ref === "string") {
    const defs = record(root.$defs) ? root.$defs : undefined;
    const target = typeof defs === "object" && defs !== null ? defs[schema.$ref.slice("#/$defs/".length)] : undefined;
    if (!record(target)) return "missing schema definition";
    return schemaError(value, target, path, root);
  }
  if (schema.const !== undefined && !Object.is(value, schema.const)) return "constant mismatch";
  if (Array.isArray(schema.enum) && !schema.enum.some((candidate) => Object.is(candidate, value))) return "enum mismatch";
  if (Array.isArray(schema.allOf)) {
    for (const part of schema.allOf) if (record(part)) {
      const error = schemaError(value, part, path, root);
      if (error !== undefined) return error;
    }
  }
  if (Array.isArray(schema.anyOf) && !schema.anyOf.some((part) => record(part) && schemaError(value, part, path, root) === undefined)) return "union mismatch";
  if (Array.isArray(schema.oneOf) && schema.oneOf.filter((part) => record(part) && schemaError(value, part, path, root) === undefined).length !== 1) return "union mismatch";
  const type = schema.type;
  if (Array.isArray(type)) {
    if (!type.some((candidate) => typeof candidate === "string" && schemaError(value, { type: candidate }, path, root) === undefined)) return "type mismatch";
    return undefined;
  }
  if (type === "null" && value !== null) return "expected null";
  if (type === "boolean" && typeof value !== "boolean") return "expected boolean";
  if (type === "string" && typeof value !== "string") return "expected string";
  if (type === "number" && (typeof value !== "number" || !Number.isFinite(value))) return "expected number";
  if (type === "integer" && (typeof value !== "number" || !Number.isInteger(value))) return "expected integer";
  if (type === "array") {
    if (!Array.isArray(value)) return "expected array";
    if (record(schema.items)) for (let index = 0; index < value.length; index += 1) {
      const error = schemaError(value[index], schema.items, path + "[" + index + "]", root);
      if (error !== undefined) return error;
    }
  }
  if (type === "object") {
    if (!record(value)) return "expected object";
    if (Array.isArray(schema.required)) for (const key of schema.required) if (typeof key === "string" && !(key in value)) return "missing required property " + key;
    const properties = record(schema.properties) ? schema.properties : {};
    for (const [key, child] of Object.entries(properties)) if (key in value && record(child)) {
      const error = schemaError(value[key], child, path + "." + key, root);
      if (error !== undefined) return error;
    }
    if (schema.additionalProperties === false) for (const key of Object.keys(value)) if (!(key in properties)) return "unexpected property " + key;
  }
  if (typeof schema.minLength === "number" && typeof value === "string" && value.length < schema.minLength) return "string too short";
  if (typeof schema.pattern === "string" && typeof value === "string" && !new RegExp(schema.pattern).test(value)) return "string pattern mismatch";
  if (typeof schema.minimum === "number" && typeof value === "number" && value < schema.minimum) return "number below minimum";
  if (typeof schema.maximum === "number" && typeof value === "number" && value > schema.maximum) return "number above maximum";
  return undefined;
}
export function isPublicPersonaResponse(value: unknown): value is GetPublicPersonasPersonaIdResponse {
  return schemaError(value, publicPersonaSchema, "$", publicPersonaSchema) === undefined;
}
