// Generated by scripts/generate-locales.mjs. Do not edit.
export const GENERATED_LOCALE_CATALOGS = {
  "ar": {
    "creation": {
      "gateWizard": {
        "actions": {
          "back": "رجوع",
          "finish": "إنهاء",
          "next": "التالي"
        },
        "checks": {
          "capability": {
            "availableNow": "متاح الآن",
            "comingLater": "قريبًا",
            "designHold": "بانتظار نموذج السياسة",
            "exploration": "استكشاف — غير مدعوم في api-next بعد"
          },
          "catalog": {
            "age18": {
              "description": "يجب أن يكون عمر الأعضاء 18 عامًا على الأقل.",
              "label": "للبالغين فقط (+18)"
            },
            "gender": {
              "description": "يثبت الأعضاء حيازة مستند يحمل علامة تسمح بها.",
              "label": "علامة الجنس في المستند"
            },
            "nationality": {
              "description": "يثبت الأعضاء حيازة مستند من بلد تسمح به.",
              "label": "الجنسية"
            },
            "nft": {
              "description": "يمتلك الأعضاء مجموعة NFT أو قطعة مقتنيات محددة.",
              "label": "رمز NFT"
            },
            "passport_score": {
              "description": "يحقق الأعضاء حدًا أدنى من نقاط Gitcoin Passport.",
              "label": "نتيجة Passport"
            },
            "token_balance": {
              "description": "يحتفظ الأعضاء بحد أدنى من رصيد أصل رقمي.",
              "label": "رصيد الرموز"
            }
          },
          "description": "يجب على الأعضاء اجتياز كل شرط تختاره، ولا توجد هنا صيغة «أحد هذه».",
          "engagementNote": "من يمكنه التفاعل — النشر والتعليق والتصويت — إعداد منفصل بعد الإنشاء.",
          "gender": {
            "emptyError": "اختر علامة واحدة على الأقل.",
            "heading": "أي العلامات؟",
            "markerF": "F — علامة أنثى",
            "markerM": "M — علامة ذكر"
          },
          "heading": "ما الشروط التي يجب أن يستوفيها الأعضاء؟",
          "nationality": {
            "countries": {
              "AU": "أستراليا",
              "BR": "البرازيل",
              "CA": "كندا",
              "CN": "الصين",
              "DE": "ألمانيا",
              "EG": "مصر",
              "FR": "فرنسا",
              "GB": "المملكة المتحدة",
              "IN": "الهند",
              "JP": "اليابان",
              "MX": "المكسيك",
              "US": "الولايات المتحدة"
            },
            "emptyError": "اختر دولة واحدة على الأقل.",
            "heading": "أي الدول؟"
          },
          "nft": {
            "categoryLabel": "الفئة",
            "categoryTradingCard": "بطاقة تجارية",
            "categoryWatch": "ساعة",
            "contractError": "أدخل عنوان عقد على الشبكة الرئيسية يبدأ بـ 0x.",
            "contractLabel": "عنوان العقد",
            "contractPlaceholder": "0x…",
            "heading": "شرط NFT",
            "minCountLabel": "الحد الأدنى للمملوك",
            "minQuantityLabel": "الحد الأدنى للكمية",
            "modeCollectible": "قطعة مقتنيات محددة",
            "modeCollection": "مجموعة NFT",
            "subjectError": "سمِّ المقتنى.",
            "subjectLabel": "المقتنى",
            "subjectPlaceholder": "مثال: لاعب أو شخصية أو علامة تجارية"
          },
          "noneSelected": "لم يتم اختيار أي شروط. يمكن لأي شخص يجتاز الخطوات أعلاه الانضمام.",
          "passportScore": {
            "error": "أدخل نتيجة صحيحة من 0 إلى 100.",
            "heading": "الحد الأدنى للنتيجة؟",
            "hint": "من 0 إلى 100.",
            "label": "الحد الأدنى لنقاط Gitcoin Passport"
          },
          "tokenBalance": {
            "amountError": "أدخل مبلغًا أكبر من صفر.",
            "amountLabel": "الحد الأدنى للرصيد",
            "amountPlaceholder": "100",
            "assetError": "أدخل معرف أصل مثل eip155:1/erc20:0x…",
            "assetLabel": "الأصل",
            "assetPlaceholder": "eip155:1/erc20:0x…",
            "heading": "أي أصل، وكم المبلغ؟"
          }
        },
        "description": "حدد من يمكنه الانضمام. تأتي قواعد النشر والتعليق والتصويت لاحقًا.",
        "invite": {
          "description": "يجتمع شرط الدعوة مع شروط العضوية معًا.",
          "heading": "هل يحتاج الأعضاء إلى دعوة؟",
          "inviteRequiredDescription": "لا يمكن الانضمام إلا للأشخاص المدعوين.",
          "inviteRequiredTitle": "الدعوة مطلوبة",
          "openDescription": "لا حاجة إلى دعوة.",
          "openTitle": "يمكن لأي شخص الانضمام"
        },
        "membership": {
          "description": "ينطبق التحقق البشري على العضوية فقط، ولا يحدد أبدًا من يمكنه النشر أو التعليق أو التصويت.",
          "heading": "من يمكنه الانضمام؟",
          "humansAndBotsDescription": "لا يُطلب التحقق البشري للانضمام.",
          "humansAndBotsTitle": "البشر والروبوتات",
          "humansOnlyDescription": "يتحقق الأعضاء من أنهم بشر قبل الانضمام.",
          "humansOnlyTitle": "البشر فقط"
        },
        "review": {
          "andNote": "يجب استيفاء كل الشرط.",
          "compiledLabel": "سياسة البوابة المُجمَّعة (معاينة مملوكة للقصة)",
          "engagementNotice": "تُضبط قواعد التفاعل للنشر والتعليق والتصويت بشكل منفصل.",
          "explorationNotice": "يتضمن هذا المسودة شروط استكشاف لا يدعمها api-next بعد.",
          "heading": "راجع العضوية",
          "openNote": "لا شروط — يمكن لأي شخص يستطيع الانضمام إلى المنصة أن يصبح عضوًا.",
          "pathLabel": "مسار الوصول 1",
          "requirements": {
            "ageMinimum": "العمر 18 عامًا على الأقل",
            "assetOwnership": "يحمل {amount} أو أكثر من {asset}",
            "erc721Collection": "يمتلك {count} أو أكثر من {contract}",
            "genderMarker": "علامة الجنس: {markers}",
            "humanVerification": "تحقق بشري",
            "inventoryMatch": "يمتلك {quantity} أو أكثر من {category}: {subject}",
            "invite": "دعوة",
            "nationalityAllowed": "مستند من: {countries}",
            "reputationScore": "نقاط Gitcoin Passport بمقدار {score} أو أكثر"
          }
        },
        "steps": {
          "checks": "الشروط",
          "invite": "الدعوة",
          "membership": "العضوية",
          "review": "المراجعة"
        },
        "title": "أنشئ مجتمعك"
      }
    },
    "feed": {
      "byAuthor": "بواسطة {author}",
      "empty": "لا توجد فيديوهات عامة حتى الآن.",
      "fallbackAuthor": "منشئ عام",
      "fallbackTitle": "فيديو عام",
      "label": "موجز الفيديو العام",
      "likeRequiresSession": "إعجاب · اتصل للتفاعل",
      "loadMore": "تحميل المزيد من الفيديوهات",
      "loadingMore": "جارٍ تحميل المزيد",
      "paginationError": "تعذر تحميل المزيد من الفيديوهات.",
      "pause": "إيقاف مؤقت",
      "play": "تشغيل",
      "retry": "إعادة المحاولة",
      "unavailable": "موجز الفيديو العام غير متاح.",
      "videoBy": "فيديو بواسطة {author}",
      "videoDescription": "وصف الفيديو",
      "videoLabel": "فيديو {title}"
    },
    "routes": {
      "home": {
        "description": "موجز فيديو بايرت ويب",
        "heading": "واجهة بايرت ويب",
        "title": "الرئيسية · بايرت ويب"
      },
      "joinRequest": {
        "description": "أخبر المشرفين لماذا تريد الانضمام.",
        "done": "تم",
        "messageOptional": "الرسالة (اختيارية)",
        "submit": "إرسال",
        "submittedDescription": "سيراجع المشرفون طلبك.",
        "submittedTitle": "تم إرسال الطلب",
        "title": "طلب الانضمام",
        "whyJoinPlaceholder": "لماذا {communityName}؟"
      },
      "moderation": {
        "links": {
          "addLink": "أضف رابطًا",
          "displayNamePlaceholder": "اسم العرض",
          "emptyState": "لا توجد روابط بعد.",
          "labelLabel": "التسمية",
          "platformLabel": "المنصة",
          "title": "الروابط",
          "urlLabel": "الرابط",
          "urlPlaceholder": "https://"
        },
        "rules": {
          "addRule": "إضافة قاعدة",
          "defaultRule1Body": "لا تحرش ولا خطاب كراهية ولا سلوك سامي. عامل جميع المساهمين والأعضاء بلطف.",
          "defaultRule1Title": "احترام الآخرين والالتزام بالأدب",
          "defaultRule2Body": "الإفراط في الترويج والرسائل المزعجة والإعلانات غير مسموح به بأي شكل.",
          "defaultRule2Title": "لا رسائل مزعجة",
          "description": "تحدد القواعد التوقعات للأعضاء والزوار في مجتمعك.",
          "descriptionPlaceholder": "الوصف",
          "emptyState": "لا توجد قواعد بعد.",
          "maxChars100": "الحد الأقصى 100 حرف",
          "maxChars500": "الحد الأقصى 500 حرف",
          "namePlaceholder": "اسم القاعدة",
          "reportReasonHint": "افتراضيًا، هذا هو نفس اسم قاعدتك.",
          "reportReasonPlaceholder": "سبب الإبلاغ",
          "reportingDescription": "يمكن للمستخدمين أو المشرفين اختيار سبب إبلاغ عند الإبلاغ عن محتوى.",
          "reportingTitle": "الإبلاغ",
          "title": "القواعد"
        },
        "saveFooter": {
          "defaultSaveLabel": "حفظ"
        }
      },
      "notFound": {
        "description": "المسار المطلوب غير موجود.",
        "returnHome": "العودة إلى الرئيسية",
        "title": "غير موجود"
      },
      "profile": {
        "createdCommunities": "المجتمعات التي تم إنشاؤها",
        "createdCommunityPluralDescription": "أنشأ {name} عدد {count} من المجتمعات على Pirate Web.",
        "createdCommunitySingularDescription": "أنشأ {name} مجتمعًا واحدًا على Pirate Web.",
        "defaultDescription": "الملف الشخصي العام لـ {name} على Pirate Web.",
        "emptyCommunities": "لم يتم إنشاء مجتمعات بعد.",
        "error": "الملف الشخصي غير متاح مؤقتًا.",
        "heading": "الملف الشخصي: @{handle}",
        "invalid": "اسم الملف الشخصي غير صالح.",
        "loading": "جارٍ تحميل الملف الشخصي",
        "notFound": "تعذر العثور على هذا الملف الشخصي.",
        "openCommunity": "فتح {name}",
        "title": "@{handle} · بايرت ويب"
      },
      "settings": {
        "booking": {
          "addAvailability": "إضافة",
          "addException": "إضافة",
          "addPriceRule": "إضافة",
          "allDays": "كل الأيام",
          "anyTime": "أي وقت",
          "autosaveNote": "تُحفظ التغييرات تلقائيًا.",
          "basePriceLabel": "السعر الأساسي (USDC)",
          "bookableLabel": "قابل للحجز",
          "bookableNoAvailability": "الحجز مفعّل، لكنك غير مرئي بعد — أضف توافرًا أسبوعيًا أدناه لتظهر في البحث والخلاصة.",
          "bookableOffHint": "لست قابلًا للحجز بعد — فعّله عندما تكون جاهزًا.",
          "bookableOnHint": "يمكن للأشخاص حجزك. أوقفه مؤقتًا دون فقدان جدولك.",
          "cancellationCopy": "يحصل الحاجزون الذين يلغون خلال 24 ساعة من الحجز على استرداد كامل؛ أما الإلغاءات اللاحقة فلا تُرد. إذا ألغيت أنت (المضيف) أو لم تحضر، يحصل الحاجز على استرداد كامل.",
          "cancellationTitle": "سياسة الإلغاء",
          "durationLabel": "مدة الجلسة",
          "durationMinutes": "{count} دقيقة",
          "exceptionBlock": "حظر",
          "exceptionOpen": "فتح",
          "exceptionsTitle": "استثناءات لمرة واحدة",
          "intro": "اسمح للأشخاص بحجز جلسات فيديو 1:1 مدفوعة معك. حدد توافرك وسعرك، ثم فعّل قابلية الحجز ليتمكنوا من حجزك من رابط ملفك الشخصي.",
          "navDescription": "حدّد جدول جلسات 1:1 المدفوعة والتسعير والتوافر.",
          "navLabel": "الحجوزات",
          "noAvailability": "لا يوجد توافر بعد — أضف فترة أسبوعية متكررة أدناه.",
          "noExceptions": "ينطبق التوافر المتكرر كما هو.",
          "noPriceRules": "ينطبق السعر الأساسي على كل وقت متاح.",
          "publish": "نشر الحجوزات",
          "publishBlockedNote": "أعدّ محفظة التطبيق لتلقي المدفوعات.",
          "publishLiveNote": "يمكن لأي شخص لديه رابط ملفك الشخصي حجز وقت متاح.",
          "publishReadyNote": "أنت جاهز — انشر ليتمكن الأشخاص من حجزك.",
          "publishTitleIdle": "انشر حجوزاتك",
          "publishTitleLive": "حجوزاتك مفعّلة",
          "rangeSeparator": "إلى",
          "remove": "إزالة",
          "saveSettings": "حفظ",
          "savingNote": "جارٍ الحفظ…",
          "sectionTitle": "حجوزات 1:1 مدفوعة",
          "timezoneLabel": "المنطقة الزمنية",
          "unpublish": "إلغاء النشر",
          "variablePricingTitle": "تسعير متغير",
          "weeklyAvailabilityTitle": "التوافر الأسبوعي"
        }
      }
    },
    "shell": {
      "appName": "بايرت ويب",
      "error": {
        "title": "واجهة التطبيق غير متاحة"
      },
      "navigation": {
        "community": "المجتمع",
        "home": "الرئيسية",
        "settings": "الإعدادات"
      }
    }
  },
  "en": {
    "creation": {
      "gateWizard": {
        "actions": {
          "back": "Back",
          "finish": "Finish",
          "next": "Next"
        },
        "checks": {
          "capability": {
            "availableNow": "Available now",
            "comingLater": "Coming later",
            "designHold": "Policy model pending",
            "exploration": "Exploration — not backed by api-next yet"
          },
          "catalog": {
            "age18": {
              "description": "Members must be at least 18 years old.",
              "label": "Adults only (18+)"
            },
            "gender": {
              "description": "Members prove a document with a marker you allow.",
              "label": "Document gender marker"
            },
            "nationality": {
              "description": "Members prove a document from a country you allow.",
              "label": "Nationality"
            },
            "nft": {
              "description": "Members own an NFT collection or a specific collectible.",
              "label": "NFT"
            },
            "passport_score": {
              "description": "Members meet a Gitcoin Passport score threshold.",
              "label": "Passport score"
            },
            "token_balance": {
              "description": "Members hold a minimum balance of an asset.",
              "label": "Token balance"
            }
          },
          "description": "Members must pass every check you select. There is no either/or logic here.",
          "engagementNote": "Who can engage — posting, commenting, and voting — is a separate setting after creation.",
          "gender": {
            "emptyError": "Select at least one marker.",
            "heading": "Which markers?",
            "markerF": "F — female marker",
            "markerM": "M — male marker"
          },
          "heading": "Which checks should members pass?",
          "nationality": {
            "countries": {
              "AU": "Australia",
              "BR": "Brazil",
              "CA": "Canada",
              "CN": "China",
              "DE": "Germany",
              "EG": "Egypt",
              "FR": "France",
              "GB": "United Kingdom",
              "IN": "India",
              "JP": "Japan",
              "MX": "Mexico",
              "US": "United States"
            },
            "emptyError": "Select at least one country.",
            "heading": "Which countries?"
          },
          "nft": {
            "categoryLabel": "Category",
            "categoryTradingCard": "Trading card",
            "categoryWatch": "Watch",
            "contractError": "Enter a mainnet contract address starting with 0x.",
            "contractLabel": "Contract address",
            "contractPlaceholder": "0x…",
            "heading": "NFT requirement",
            "minCountLabel": "Minimum owned",
            "minQuantityLabel": "Minimum quantity",
            "modeCollectible": "A specific collectible",
            "modeCollection": "An NFT collection",
            "subjectError": "Name the collectible.",
            "subjectLabel": "Collectible",
            "subjectPlaceholder": "e.g. a player, character, or brand"
          },
          "noneSelected": "No checks selected. Anyone who passes the steps above can join.",
          "passportScore": {
            "error": "Enter a whole score from 0 to 100.",
            "heading": "Minimum score?",
            "hint": "From 0 to 100.",
            "label": "Minimum Gitcoin Passport score"
          },
          "tokenBalance": {
            "amountError": "Enter an amount greater than zero.",
            "amountLabel": "Minimum balance",
            "amountPlaceholder": "100",
            "assetError": "Enter an asset id like eip155:1/erc20:0x…",
            "assetLabel": "Asset",
            "assetPlaceholder": "eip155:1/erc20:0x…",
            "heading": "Which asset, and how much?"
          }
        },
        "description": "Set who can join. Posting, commenting, and voting rules come later.",
        "invite": {
          "description": "An invitation requirement combines with the membership checks.",
          "heading": "Do members need an invitation?",
          "inviteRequiredDescription": "Only invited people can join.",
          "inviteRequiredTitle": "Invitation required",
          "openDescription": "No invitation is needed.",
          "openTitle": "Anyone may join"
        },
        "membership": {
          "description": "Human verification applies to membership only. It never decides who can post, comment, or vote.",
          "heading": "Who can join?",
          "humansAndBotsDescription": "No human verification is required to join.",
          "humansAndBotsTitle": "Humans and bots",
          "humansOnlyDescription": "Members verify they are human before they join.",
          "humansOnlyTitle": "Humans only"
        },
        "review": {
          "andNote": "Every requirement must pass.",
          "compiledLabel": "Compiled gate policy (story-owned preview)",
          "engagementNotice": "Engagement rules for posting, commenting, and voting are configured separately.",
          "explorationNotice": "This draft includes exploration checks that api-next does not support yet.",
          "heading": "Review membership",
          "openNote": "No requirements — anyone who can join the platform may become a member.",
          "pathLabel": "Access path 1",
          "requirements": {
            "ageMinimum": "At least 18 years old",
            "assetOwnership": "Holds {amount} or more of {asset}",
            "erc721Collection": "Owns {count} or more from {contract}",
            "genderMarker": "Gender marker: {markers}",
            "humanVerification": "Verified human",
            "inventoryMatch": "Owns {quantity} or more {category}: {subject}",
            "invite": "Invitation",
            "nationalityAllowed": "Document from: {countries}",
            "reputationScore": "Gitcoin Passport score of {score} or more"
          }
        },
        "steps": {
          "checks": "Checks",
          "invite": "Invite",
          "membership": "Membership",
          "review": "Review"
        },
        "title": "Create your community"
      }
    },
    "feed": {
      "byAuthor": "by {author}",
      "empty": "No public videos are available yet.",
      "fallbackAuthor": "public creator",
      "fallbackTitle": "Public video",
      "label": "Public video feed",
      "likeRequiresSession": "Like · connect to act",
      "loadMore": "Load more videos",
      "loadingMore": "Loading more",
      "paginationError": "More videos could not be loaded.",
      "pause": "Pause",
      "play": "Play",
      "retry": "Retry",
      "unavailable": "The public video feed is unavailable.",
      "videoBy": "Video by {author}",
      "videoDescription": "Video description",
      "videoLabel": "{title} video"
    },
    "routes": {
      "home": {
        "description": "Pirate Web video feed",
        "heading": "Pirate Web Solid shell",
        "title": "Home · Pirate Web"
      },
      "joinRequest": {
        "description": "Tell the moderators why you want to join. Include links or proof that show you are eligible.",
        "done": "Done",
        "messageOptional": "Message (Optional)",
        "submit": "Submit",
        "submittedDescription": "The moderators will review your request.",
        "submittedTitle": "Request submitted",
        "title": "Request to join",
        "whyJoinPlaceholder": "Why {communityName}?"
      },
      "moderation": {
        "links": {
          "addLink": "Add link",
          "displayNamePlaceholder": "Display name",
          "emptyState": "No links yet.",
          "labelLabel": "Label",
          "platformLabel": "Platform",
          "title": "Links",
          "urlLabel": "URL",
          "urlPlaceholder": "https://"
        },
        "rules": {
          "addRule": "Add rule",
          "defaultRule1Body": "No harassment, hate speech, or toxic behavior. Treat all contributors and members with kindness.",
          "defaultRule1Title": "Respect others and be civil",
          "defaultRule2Body": "Excessive promotion, spam, or advertising of any kind is not allowed.",
          "defaultRule2Title": "No spam",
          "description": "Rules set the expectations for members and visitors in your community.",
          "descriptionPlaceholder": "Description",
          "emptyState": "No rules yet.",
          "maxChars100": "Max characters 100",
          "maxChars500": "Max characters 500",
          "namePlaceholder": "Rule name",
          "reportReasonHint": "By default, this is the same as your rule name.",
          "reportReasonPlaceholder": "Report reason",
          "reportingDescription": "Users or mods can select a report reason when reporting content.",
          "reportingTitle": "Reporting",
          "title": "Rules"
        },
        "saveFooter": {
          "defaultSaveLabel": "Save"
        }
      },
      "notFound": {
        "description": "The requested route does not exist.",
        "returnHome": "Return home",
        "title": "Not found"
      },
      "profile": {
        "createdCommunities": "Created communities",
        "createdCommunityPluralDescription": "{name} created {count} communities on Pirate Web.",
        "createdCommunitySingularDescription": "{name} created 1 community on Pirate Web.",
        "defaultDescription": "Public profile for {name} on Pirate Web.",
        "emptyCommunities": "No communities created yet.",
        "error": "This profile is temporarily unavailable.",
        "heading": "Profile: @{handle}",
        "invalid": "That profile handle is not valid.",
        "loading": "Loading profile",
        "notFound": "This profile could not be found.",
        "openCommunity": "Open {name}",
        "title": "@{handle} · Pirate Web"
      },
      "settings": {
        "booking": {
          "addAvailability": "Add",
          "addException": "Add",
          "addPriceRule": "Add",
          "allDays": "All days",
          "anyTime": "Any",
          "autosaveNote": "Changes save automatically.",
          "basePriceLabel": "Base price (USDC)",
          "bookableLabel": "Bookable",
          "bookableNoAvailability": "Bookable is on, but you're not visible yet — add weekly availability below to appear in search and feed.",
          "bookableOffHint": "You're not bookable yet — turn on when you're ready.",
          "bookableOnHint": "People can book you. Turn off to pause without losing your schedule.",
          "cancellationCopy": "Bookers receive a full refund when they cancel at least 24 hours before the session starts. Cancellations made less than 24 hours before the session are non-refundable. If you (the host) cancel or do not attend, the booker receives a full refund.",
          "cancellationTitle": "Cancellation policy",
          "durationLabel": "Session length",
          "durationMinutes": "{count} minutes",
          "exceptionBlock": "Block",
          "exceptionOpen": "Open",
          "exceptionsTitle": "One-off exceptions",
          "intro": "Let people book paid 1:1 video sessions with you. Set your availability and price, then turn on Bookable to become bookable from your profile link.",
          "navDescription": "Set your paid 1:1 schedule, pricing, and availability.",
          "navLabel": "Bookings",
          "noAvailability": "No availability yet — add a recurring weekly window below.",
          "noExceptions": "Recurring availability applies as-is.",
          "noPriceRules": "Base price applies to every available slot.",
          "publish": "Publish bookings",
          "publishBlockedNote": "Set up your app wallet to receive payouts.",
          "publishLiveNote": "Anyone with your profile link can book an available slot.",
          "publishReadyNote": "You're ready — publish to let people book you.",
          "publishTitleIdle": "Publish your bookings",
          "publishTitleLive": "Your bookings are live",
          "rangeSeparator": "to",
          "remove": "Remove",
          "saveSettings": "Save",
          "savingNote": "Saving…",
          "sectionTitle": "Paid 1:1 bookings",
          "timezoneLabel": "Timezone",
          "unpublish": "Unpublish",
          "variablePricingTitle": "Variable pricing",
          "weeklyAvailabilityTitle": "Weekly availability"
        }
      }
    },
    "shell": {
      "appName": "Pirate Web",
      "error": {
        "title": "App shell unavailable"
      },
      "navigation": {
        "community": "Community",
        "home": "Home",
        "settings": "Settings"
      }
    }
  },
  "zh": {
    "creation": {
      "gateWizard": {
        "actions": {
          "back": "上一步",
          "finish": "完成",
          "next": "下一步"
        },
        "checks": {
          "capability": {
            "availableNow": "现已可用",
            "comingLater": "即将推出",
            "designHold": "策略模型待定",
            "exploration": "探索性——api-next 尚不支持"
          },
          "catalog": {
            "age18": {
              "description": "成员必须年满 18 岁。",
              "label": "仅限成年人（18+）"
            },
            "gender": {
              "description": "成员需证明持有带有你允许的标记的证件。",
              "label": "证件性别标记"
            },
            "nationality": {
              "description": "成员需证明持有你允许的国家/地区的证件。",
              "label": "国籍"
            },
            "nft": {
              "description": "成员拥有一个 NFT 收藏集或特定藏品。",
              "label": "NFT"
            },
            "passport_score": {
              "description": "成员达到 Gitcoin Passport 分数门槛。",
              "label": "Passport 分数"
            },
            "token_balance": {
              "description": "成员持有某资产的最低余额。",
              "label": "代币余额"
            }
          },
          "description": "成员必须通过你选择的每一项条件，这里没有“任选其一”的逻辑。",
          "engagementNote": "谁能互动——发帖、评论和投票——是创建后的独立设置。",
          "gender": {
            "emptyError": "请至少选择一个标记。",
            "heading": "哪些标记？",
            "markerF": "F — 女性标记",
            "markerM": "M — 男性标记"
          },
          "heading": "成员需要通过哪些条件？",
          "nationality": {
            "countries": {
              "AU": "澳大利亚",
              "BR": "巴西",
              "CA": "加拿大",
              "CN": "中国",
              "DE": "德国",
              "EG": "埃及",
              "FR": "法国",
              "GB": "英国",
              "IN": "印度",
              "JP": "日本",
              "MX": "墨西哥",
              "US": "美国"
            },
            "emptyError": "请至少选择一个国家/地区。",
            "heading": "哪些国家/地区？"
          },
          "nft": {
            "categoryLabel": "类别",
            "categoryTradingCard": "交易卡",
            "categoryWatch": "腕表",
            "contractError": "请输入以 0x 开头的主网合约地址。",
            "contractLabel": "合约地址",
            "contractPlaceholder": "0x…",
            "heading": "NFT 条件",
            "minCountLabel": "最少持有数量",
            "minQuantityLabel": "最少数量",
            "modeCollectible": "特定藏品",
            "modeCollection": "一个 NFT 收藏集",
            "subjectError": "请填写藏品名称。",
            "subjectLabel": "藏品",
            "subjectPlaceholder": "例如球员、角色或品牌"
          },
          "noneSelected": "未选择任何条件。通过上述步骤的任何人都可以加入。",
          "passportScore": {
            "error": "请输入 0 到 100 之间的整数。",
            "heading": "最低分数？",
            "hint": "0 到 100。",
            "label": "最低 Gitcoin Passport 分数"
          },
          "tokenBalance": {
            "amountError": "请输入大于零的数量。",
            "amountLabel": "最低余额",
            "amountPlaceholder": "100",
            "assetError": "请输入形如 eip155:1/erc20:0x… 的资产 ID。",
            "assetLabel": "资产",
            "assetPlaceholder": "eip155:1/erc20:0x…",
            "heading": "哪个资产，多少数量？"
          }
        },
        "description": "设置谁可以加入。发帖、评论和投票规则稍后配置。",
        "invite": {
          "description": "邀请要求与成员条件同时生效。",
          "heading": "成员需要邀请吗？",
          "inviteRequiredDescription": "只有受邀请的人才能加入。",
          "inviteRequiredTitle": "需要邀请",
          "openDescription": "无需邀请。",
          "openTitle": "任何人都可以加入"
        },
        "membership": {
          "description": "真人验证仅适用于成员资格，绝不决定谁可以发帖、评论或投票。",
          "heading": "谁可以加入？",
          "humansAndBotsDescription": "加入无需真人验证。",
          "humansAndBotsTitle": "真人和机器人",
          "humansOnlyDescription": "成员加入前需验证自己是真人。",
          "humansOnlyTitle": "仅限真人"
        },
        "review": {
          "andNote": "每项条件都必须满足。",
          "compiledLabel": "编译后的门槛策略（Story 专属预览）",
          "engagementNotice": "发帖、评论和投票的互动规则将单独配置。",
          "explorationNotice": "此草案包含 api-next 尚不支持的探索性条件。",
          "heading": "确认成员资格",
          "openNote": "没有任何条件——平台上可加入的任何人都可以成为成员。",
          "pathLabel": "加入路径 1",
          "requirements": {
            "ageMinimum": "年满 18 岁",
            "assetOwnership": "持有 {amount} 或更多 {asset}",
            "erc721Collection": "持有 {contract} 的 {count} 个或更多",
            "genderMarker": "性别标记：{markers}",
            "humanVerification": "真人验证",
            "inventoryMatch": "持有 {quantity} 个或更多 {category}：{subject}",
            "invite": "邀请",
            "nationalityAllowed": "证件来自：{countries}",
            "reputationScore": "Gitcoin Passport 分数不低于 {score}"
          }
        },
        "steps": {
          "checks": "条件",
          "invite": "邀请",
          "membership": "成员资格",
          "review": "确认"
        },
        "title": "创建你的社区"
      }
    },
    "feed": {
      "byAuthor": "作者：{author}",
      "empty": "暂时没有公开视频。",
      "fallbackAuthor": "公开视频作者",
      "fallbackTitle": "公开视频",
      "label": "公开视频动态",
      "likeRequiresSession": "点赞 · 登录后操作",
      "loadMore": "加载更多视频",
      "loadingMore": "正在加载更多",
      "paginationError": "无法加载更多视频。",
      "pause": "暂停",
      "play": "播放",
      "retry": "重试",
      "unavailable": "公开视频动态暂不可用。",
      "videoBy": "{author} 的视频",
      "videoDescription": "视频描述",
      "videoLabel": "{title} 视频"
    },
    "routes": {
      "home": {
        "description": "Pirate Web 视频动态",
        "heading": "Pirate Web Solid 界面",
        "title": "首页 · Pirate Web"
      },
      "joinRequest": {
        "description": "告诉版主你为什么想加入。",
        "done": "完成",
        "messageOptional": "留言（可选）",
        "submit": "提交",
        "submittedDescription": "版主将审核你的申请。",
        "submittedTitle": "申请已提交",
        "title": "申请加入",
        "whyJoinPlaceholder": "为什么想加入 {communityName}？"
      },
      "moderation": {
        "links": {
          "addLink": "添加链接",
          "displayNamePlaceholder": "显示名称",
          "emptyState": "还没有链接。",
          "labelLabel": "标签",
          "platformLabel": "平台",
          "title": "链接",
          "urlLabel": "链接",
          "urlPlaceholder": "https://"
        },
        "rules": {
          "addRule": "添加规则",
          "defaultRule1Body": "禁止骚扰、仇恨言论或任何有害行为。请友善对待所有贡献者和成员。",
          "defaultRule1Title": "尊重他人，文明交流",
          "defaultRule2Body": "不允许任何形式的过度推广、垃圾信息或广告。",
          "defaultRule2Title": "禁止垃圾信息",
          "description": "规则为社区中的成员和访客设定期望。",
          "descriptionPlaceholder": "描述",
          "emptyState": "还没有规则。",
          "maxChars100": "最多 100 个字符",
          "maxChars500": "最多 500 个字符",
          "namePlaceholder": "规则名称",
          "reportReasonHint": "默认情况下，这与你的规则名称相同。",
          "reportReasonPlaceholder": "举报原因",
          "reportingDescription": "用户或版主在举报内容时可以选择举报原因。",
          "reportingTitle": "举报",
          "title": "规则"
        },
        "saveFooter": {
          "defaultSaveLabel": "保存"
        }
      },
      "notFound": {
        "description": "请求的页面不存在。",
        "returnHome": "返回首页",
        "title": "未找到"
      },
      "profile": {
        "createdCommunities": "已创建的社区",
        "createdCommunityPluralDescription": "{name} 在 Pirate Web 创建了 {count} 个社区。",
        "createdCommunitySingularDescription": "{name} 在 Pirate Web 创建了 1 个社区。",
        "defaultDescription": "{name} 在 Pirate Web 的公开个人资料。",
        "emptyCommunities": "尚未创建社区。",
        "error": "该个人资料暂时不可用。",
        "heading": "个人资料：@{handle}",
        "invalid": "该个人资料句柄无效。",
        "loading": "正在加载个人资料",
        "notFound": "找不到该个人资料。",
        "openCommunity": "打开 {name}",
        "title": "@{handle} · Pirate Web"
      },
      "settings": {
        "booking": {
          "addAvailability": "添加",
          "addException": "添加",
          "addPriceRule": "添加",
          "allDays": "所有日期",
          "anyTime": "任意时间",
          "autosaveNote": "更改会自动保存。",
          "basePriceLabel": "基础价格 (USDC)",
          "bookableLabel": "可预约",
          "bookableNoAvailability": "可预约已开启，但你还不会显示 — 在下方添加每周重复时段，才会出现在搜索和动态中。",
          "bookableOffHint": "你还不可预约 — 准备好后再开启。",
          "bookableOnHint": "人们可以预约你。关闭后可暂停预约，且不会丢失你的日程。",
          "cancellationCopy": "预约者在预约后 24 小时内取消可获得全额退款；之后取消不予退款。如果你（主持人）取消或未出席，预约者将获得全额退款。",
          "cancellationTitle": "取消政策",
          "durationLabel": "会话时长",
          "durationMinutes": "{count} 分钟",
          "exceptionBlock": "屏蔽",
          "exceptionOpen": "开放",
          "exceptionsTitle": "一次性例外",
          "intro": "让人们预约与你进行付费 1:1 视频会话。设置可预约时间和价格，然后开启“可预约”，即可通过你的个人资料链接接受预约。",
          "navDescription": "设置你的付费 1:1 日程、价格和可预约时间。",
          "navLabel": "预约",
          "noAvailability": "还没有可预约时间 — 在下方添加一个每周重复时段。",
          "noExceptions": "重复可预约时间将照常适用。",
          "noPriceRules": "基础价格适用于所有可预约时段。",
          "publish": "发布预约",
          "publishBlockedNote": "设置你的应用钱包以接收款项。",
          "publishLiveNote": "拥有你个人资料链接的任何人都可以预约可用时段。",
          "publishReadyNote": "你已准备好 — 发布后人们就可以预约你。",
          "publishTitleIdle": "发布你的预约",
          "publishTitleLive": "你的预约已上线",
          "rangeSeparator": "至",
          "remove": "移除",
          "saveSettings": "保存",
          "savingNote": "正在保存…",
          "sectionTitle": "付费 1:1 预约",
          "timezoneLabel": "时区",
          "unpublish": "取消发布",
          "variablePricingTitle": "浮动定价",
          "weeklyAvailabilityTitle": "每周可预约时间"
        }
      }
    },
    "shell": {
      "appName": "Pirate Web",
      "error": {
        "title": "应用界面暂不可用"
      },
      "navigation": {
        "community": "社区",
        "home": "首页",
        "settings": "设置"
      }
    }
  }
} as const;

export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
export type RealLocaleCode = keyof GeneratedLocaleCatalogs;
export type LocaleNamespace = keyof GeneratedLocaleCatalogs["en"];
