#!/usr/bin/env python3
"""Extract the one endpoint's generated validator; report drift by default."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import tarfile


def digest(value):
    return hashlib.sha256(value).hexdigest()


def extract(root):
    package = json.loads((root / "package.json").read_bytes())
    descriptor = package["dependencies"]["@pirate/api-client"]
    if not re.fullmatch(r"file:vendor/api-client/pirate-api-client-\d+\.\d+\.\d+(?:-[a-f0-9]{8})?\.tgz", descriptor):
        raise ValueError("unpinned client artifact")
    artifact = root / descriptor.removeprefix("file:")
    if artifact.is_symlink():
        raise ValueError("symlinked client artifact")
    with tarfile.open(artifact) as archive:
        member = archive.getmember("package/src/generated/client.ts")
        if not member.isfile() or member.size > 16 * 1024 * 1024:
            raise ValueError("invalid generated client member")
        source = archive.extractfile(member).read()
        version = json.load(archive.extractfile("package/package.json"))["version"]
    text = source.decode()
    table = text.index("const RESPONSE_SCHEMAS: Record<string, JsonSchema> = {")
    key = '  "get_publicPersonasPersonaId": '
    start = text.index(key, table) + len(key)
    schema, length = json.JSONDecoder().raw_decode(text[start:])
    if text[start + length:start + length + 2] != ",\n":
        raise ValueError("unexpected generated schema framing")
    start = text.index("function record(")
    end = text.index("function parseWireError(", start)
    algorithm = text[start:end]
    if algorithm.count("function ") != 2:
        raise ValueError("generated validator algorithm changed framing")
    schema_bytes = (json.dumps(schema, separators=(",", ":"), ensure_ascii=False) + "\n").encode()
    schema_module = ("// Generated by scripts/hns-public-persona-validator.py --write.\n"
                     "// Deliberately frozen; the client drift report never changes these bytes.\n"
                     "/* oxlint-disable anti-slop/no-unsafe-dictionary-type, anti-slop/no-known-value-widening -- Preserve the reviewed generated schema representation exactly. */\n"
                     "export const publicPersonaSchema: Record<string, unknown> = " +
                     json.dumps(schema, indent=2, ensure_ascii=False) + ";\n").encode()
    module = ("// Generated by scripts/hns-public-persona-validator.py --write.\n"
              "// The algorithm below is byte-identical to the reviewed client implementation.\n"
              "/* oxlint-disable anti-slop/no-unsafe-dictionary-type -- This frozen generated algorithm validates unknown JSON at the wire boundary. */\n"
              'import { publicPersonaSchema } from "./public-persona-schema.ts";\n'
              'import type { GetPublicPersonasPersonaIdResponse } from "@pirate/api-client";\n'
              "type JsonSchema = Record<string, unknown>;\n" + algorithm +
              "export function isPublicPersonaResponse(value: unknown): value is GetPublicPersonasPersonaIdResponse {\n"
              '  return schemaError(value, publicPersonaSchema, "$", publicPersonaSchema) === undefined;\n'
              "}\n").encode()
    provenance = {"schema": "hns-public-persona-validator-provenance-v1", "operation": "get_publicPersonasPersonaId",
                  "clientVersion": version, "artifact": descriptor, "artifactSha256": digest(artifact.read_bytes()),
                  "generatedSourceSha256": digest(source), "endpointSchemaSha256": digest(schema_bytes),
                  "validatorAlgorithmSha256": digest(algorithm.encode()), "schemaModuleSha256": digest(schema_module),
                  "validatorModuleSha256": digest(module), "extraction": "python3 scripts/hns-public-persona-validator.py --write"}
    return module, schema_module, provenance


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Deliberately replace frozen ingress files; requires review")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    target = root / "src/hns-ingress/public-persona-validator"
    module, schema, current = extract(root)
    if args.write:
        target.mkdir(exist_ok=True)
        (target / "public-persona-schema.ts").write_bytes(schema)
        (target / "public-persona-validator.ts").write_bytes(module)
        (target / "provenance.json").write_text(json.dumps(current, indent=2) + "\n")
        print(json.dumps({"vendored": True, "provenance": current}))
        return
    frozen = json.loads((target / "provenance.json").read_bytes())
    integrity = digest((target / "public-persona-schema.ts").read_bytes()) == frozen["schemaModuleSha256"] and digest((target / "public-persona-validator.ts").read_bytes()) == frozen["validatorModuleSha256"]
    drift = {key: current[key] != frozen[key] for key in ("endpointSchemaSha256", "validatorAlgorithmSha256")}
    print(json.dumps({"frozenIntegrity": integrity, "drift": drift, "currentClientVersion": current["clientVersion"], "frozenClientVersion": frozen["clientVersion"], "writes": False}))
    if not integrity:
        raise SystemExit("frozen validator integrity mismatch")
    if any(drift.values()):
        print("Ingress endpoint drift requires deliberate review and re-vendoring; frozen bytes were retained.")


if __name__ == "__main__":
    main()
